### ISSUE TITLE
Incorrect error message for weak account password

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_examples#125]
When creating a new account, the following error message displayed when the password is weak: "Account **secret** needs to be stronger". This message should instead read "Account **password** needs to be stronger"

**Comment by bochaco** [comment]
This is a minor issue and I created just to use it for ramping up on SAFE code, I'll be willing to fix it in the next few days as an exercise.

**Comment by krishnaIndia** [comment]
Will get this patched in [safe_launcher](https://github.com/maidsafe/safe_launcher). Thanks @bochaco

**Comment by krishnaIndia** [comment]
This should be fixed in the launcher [version 0.9.1](https://github.com/maidsafe/safe_launcher/releases/tag/0.9.1)
