### ISSUE TITLE
directory not visible in SAFE Demo App v0.6.1

### ISSUE THREAD

**Issue by Yerontour** [maidsafe/safe_examples#134]
I created a directory via the API with SAFE Launcher v0.9.1 and postman:
POST: http://localhost:8100/nfs/directory/drive/myapp 

and it is visible with with this API call:
GET: http://localhost:8100/nfs/directory/drive/myapp

but the directory doesn't show up in the SAFE Demo App v0.6.1

I created the auth token with:
{
    "app": {
        "name": "MyFirst",
        "id": "MyApp",
        "version": "0.0.1",
        "vendor": "MaidSafe"
    },
    "permissions": [
        "SAFE_DRIVE_ACCESS"
    ]
}

**Comment by krishnaIndia** [comment]
Thanks for trying out the apis @Yerontour.

The Demo app does not retrieve data from SAFE Drive. Demo app stores and retrieves files only from the applications root directory. 

The directory structure of demo app is,
```
         App_Root_Directory
                  |
   ----------------------
   |                      |
Public              Private
```
These two folders are created at the first time when the applications load and the demo app is programmed to read and display files only from these two folders.

You can create a folder in the demo app using 
`POST: http://localhost:8100/nfs/directory/app/public/myapp`
