### ISSUE TITLE
TEST10: Demo App v0.6.1 - Failed to fetch Directory

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_examples#135]
So, returning to a directory that was uploaded around the start of TEST10, Demo App now gives Operation Failed FfiError:PathNotFound:
![screenshot at 2016-10-17 21 09 44](https://cloud.githubusercontent.com/assets/1708690/19453850/da27f7f8-94ae-11e6-9ca1-6ec07aa7292d.jpg)

that was for folder containing diy.yvette .. the files appear to be still available to download.

I had the same on dir.yvette but remapped that to a new upload. Perhaps then more instances of older directories uploaded have this issue now?

**Comment by krishnaIndia** [comment]
@davidpbrown, can you please confirm the demo app version? Please use the latest demo app version, the `id` of the demo app was updated and this will result in a new root directory for the application. The old versions have a different root directory from the latest version.

I am assuming that this can happen when latest version of demo app was used initially to upload and now an old version is being used. The version which was used to upload the files should be able to fetch the files properly.

**Comment by davidpbrown** [comment]
safe-demo-app-v0.6.1-linux-x64

It's not confusion with the version; the Alpha and TEST10 are on different computers.

I just took another look and now see a different result for which directories it can access:
[Manage Websites].[Edit Files] does now see files for diy.yvette and www.yvette but not the remapped dir2.yvette that I created and mapped to yesterday.

So, going deeper there's something odd going on that I can't make sense of..
1. [Manage Websites].[Edit Files] -> gives error.
2. Click OK -> gives an empty listing titled /public/dir2.yvette 
3. Click up-arrow, for parent directory -> lists all but not any dir2.yvette.. and sees dir.yvette which I didn't delete.

but where then is the folder of dir2.yvette that safe://dir.yvette is still mapped to? SAFE Beaker Browser finds that page but why does Demo App not find the source files for dir2.yvette??

and the second query becomes, why is the result of [Manage Websites].[Edit Files] tonight the inverse of last night.. that I can see folders today that I could not yesterday; and visa versa.

**Comment by davidpbrown** [comment]
The terminal detail below for an attempt on that missing/not-missing directory:
```
DEBUG 17:58:50.112 - Authorised request ::/nfs/directory/app//public/dir2.yvette/
DEBUG 17:58:50.113 - Decrypted session id :: baauAGN0f9ZT+egTQ/zxrjbewqhPNkvrV7uXJKLxVbk=
DEBUG 17:58:50.114 - NFS  - Invoking get directory request
TRACE 16:58:50.114767387 [safe_core::ffi::nfs::dir dir.rs:82] FFI get dir, given the path.
TRACE 16:58:50.114808114 [safe_core::ffi::helper helper.rs:136] Traverse directory tree to get the final subdirectory.
TRACE 16:58:50.114816487 [safe_core::ffi::helper helper.rs:142] Traversal begins at given starting directory.
TRACE 16:58:50.114823973 [safe_core::nfs::helper::directory_helper directory_helper.rs:164] Getting an unversioned directory listing.
DEBUG 16:58:50.114836569 [safe_core::nfs::helper::directory_helper directory_helper.rs:393] Getting structured data from the network ...
TRACE 16:58:50.114844791 [safe_core::core::client mod.rs:362] GET for Structured(3d50f2.., 15101)
TRACE 16:58:50.194797715 [safe_core::core::client::message_queue message_queue.rs:150] EventReceiverThread received: Event::Response { response: GetSuccess(StructuredData { type_tag: 15101, name: 3d50f2.., data: 000000..524146, previous_owner_keys: [], version: 9, current_owner_keys: ["54935c..0b75b2"], previous_owner_signatures: ["e7b087..82d303"] }, MessageId(91ef3c..)), src: NaeManager(name: 3d50f2..), dst: Client { client_name: 87fbc7.., proxy_node_name: 662ae8.., peer_id: PeerId(4b6b..) } }
TRACE 16:58:50.194963210 [safe_core::core::structured_data_operations::unversioned unversioned.rs:144] Getting unversioned StructuredData
TRACE 16:58:50.195532163 [safe_core::ffi::helper helper.rs:152] Traversing to dir with name: public
TRACE 16:58:50.195544816 [safe_core::nfs::helper::directory_helper directory_helper.rs:164] Getting an unversioned directory listing.
DEBUG 16:58:50.195552786 [safe_core::nfs::helper::directory_helper directory_helper.rs:393] Getting structured data from the network ...
TRACE 16:58:50.195561571 [safe_core::core::client mod.rs:362] GET for Structured(096856.., 15101)
TRACE 16:58:50.353593845 [safe_core::core::client::message_queue message_queue.rs:150] EventReceiverThread received: Event::Response { response: GetSuccess(StructuredData { type_tag: 15101, name: 096856.., data: 000000..000000, previous_owner_keys: [], version: 76, current_owner_keys: ["54935c..0b75b2"], previous_owner_signatures: ["853b1d..13ab01"] }, MessageId(f6ad0d..)), src: NaeManager(name: 096856..), dst: Client { client_name: 87fbc7.., proxy_node_name: 662ae8.., peer_id: PeerId(4b6b..) } }
TRACE 16:58:50.353760071 [safe_core::core::structured_data_operations::unversioned unversioned.rs:144] Getting unversioned StructuredData
TRACE 16:58:50.353824651 [safe_core::ffi::helper helper.rs:152] Traversing to dir with name: dir2.yvette
INFO 16:58:50.353839132 [safe_core::ffi::nfs::dir dir.rs:84] 
FFI cross-boundary error propagation:
 --------------------------------------------------
| **ERRNO: -1502** FfiError::PathNotFound
 --------------------------------------------------


WARN 17:58:50.355 - Err 404 - Msg :: [object Object]
TRACE 16:58:54.894821870 [safe_core::ffi::session session.rs:225] FFI retrieve client issued GETs.
TRACE 16:58:54.895161191 [safe_core::ffi::session session.rs:236] FFI retrieve client issued PUTs.
TRACE 16:58:54.896848596 [safe_core::ffi::session session.rs:247] FFI retrieve client issued POSTs.
TRACE 16:58:54.897205438 [safe_core::ffi::session session.rs:258] FFI retrieve client issued DELETEs.

```

**Comment by Viv-Rajkumar** [comment]
Hey @davidpbrown, just to test can you try using `safe-demo-app v0.6.0`instead of `0.6.1` with the same launcher you're using for TEST-10 please and check what you see in the public folders section?

**Comment by davidpbrown** [comment]
Ok.. so, I've done a fair amount of switching back and forward just now to check this.
The result has changed again and I can atm see safe://dir.yvette == dir2.yvette in both versions.. as far as I could tell result is identical in both; so, www.yvette and diy.yvette and currently not available. Which seems then to be the inverse of 2hrs ago!?

**Comment by krishnaIndia** [comment]
@davidpbrown, I ll ping you in the forum.

**Comment by krishnaIndia** [comment]
@davidpbrown, the issue is with the demo app version mismatch.

To test this, start a demo app version 0.6.0 and you can check the files. Then revoke demo app access from launcher and start the demo app version 0.6.1

Can not reproduce this issue without revoking the access because the demo app is using the cached auth token.

Here are the images of demo app from v0.6.0 and v0.6.1
![v0 6 0](https://cloud.githubusercontent.com/assets/7702996/19519989/ff73a4a2-962b-11e6-837b-cb89c73bd6af.png)
![v0 6 1](https://cloud.githubusercontent.com/assets/7702996/19519994/04a2428a-962c-11e6-8a72-65743a5114a8.png)

**Comment by davidpbrown** [comment]
Did you test all three of dir. diy. and www. ? Persistently one of those is failing with the error.

Tonight though, I'm getting different results following what you suggested as test.

TEST10+6.1 sees dir.yvette fail - with diy. and www. ok 
TEST10+6.0 sees diy.yvette and www. fail - with dir. ok 

dir TEST10 + 6.1
![dir test10 6 1](https://cloud.githubusercontent.com/assets/1708690/19530542/2d200c92-962c-11e6-8caa-6550f8c3858a.jpg)

and following with up arrow in 6.1 sees:
![test10 6 1 after uparrow](https://cloud.githubusercontent.com/assets/1708690/19530546/33731eae-962c-11e6-8bae-30dc83be4d94.jpg)

======

diy TEST10 + 6.0
![diy test10 6 0](https://cloud.githubusercontent.com/assets/1708690/19530556/4027698e-962c-11e6-8b59-218f011f737d.jpg)

and www TEST10 + 6.0
![www test10 6 0](https://cloud.githubusercontent.com/assets/1708690/19530560/43c62bac-962c-11e6-9995-b8715c4be883.jpg)

and following with up arrow in 6.0 sees:
![test10 6 0 after uparrow](https://cloud.githubusercontent.com/assets/1708690/19530580/55ea0c22-962c-11e6-936f-f0437177b2a0.jpg)

None of which makes sense.

I shouldn't see those errors.. and if I did would expect them to be more consistent, relative to the beaker browser seeing all three sites in TEST10.

So, I don't understand how this is a "demo app version mismatch".. nice theory but I don't think I can have confused them with not having the 6.0 against TEST10 before suggested above that I try the difference.

One answer of course is if there's an issue it'll likely repeat TEST11+ and can watch for it.

**Comment by krishnaIndia** [comment]
v0.6.0 has the folder `dir2.` while the other folders are uploaded using v.0.6.1 (`dir.` & `www.`).
This can be clearly seen from the screen shots I had posted.

> So, I don't understand how this is a "demo app version mismatch"

In the version update of 0.6.1 the `id` of the demo app was updated. The application root folder is generated based on the `app name + id + vendor name` combination. Since the `id` has changed in version 0.6.1, the root folder is completely new.

You can consider, demo app version 0.6.0 as a different app from 0.6.1. They both have different root directories. Data uploaded in 0.6.0 can not be accessed in 0.6.1 and vice versa too.

> TEST10+6.1 sees dir.yvette fail - with diy. and www. ok 

`dir.` fails because the directory contents('dir2.yvette') are uploaded using v0.6.0.

> TEST10+6.0 sees diy.yvette and www. fail - with dir. ok

`diy.yvette and www.` fail because the folders mapped to the service are uploaded using v0.6.1. v0.6.0 can not find it within its root directory. 

*Solution:*
You can upload the `dir2.` directory using the v0.6.1. Remap the service `dir.yvette` to the uploaded `dir2.` directory again. This will start pointing to the `dir2.` folder in the demo app v0.6.1

**Comment by davidpbrown** [comment]
Ok.. seems then user error, which is a good outcome. thanks.
