### ISSUE TITLE
Safe signaling demo - Save Structured Data PUT Failure - Windows

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_examples#141]
Using Launcher 0.9.3, Safe Browser 0.3.6-2, Windows 10. Going to safe://mediawebrtc.ben/#hundef+swikith and authorising use of camera / mic I see video footage of myself on the screen from the web cam bottom right but the  "connecting" message remains just below the blue bar at the top of the screen. Meanwhile, in the launcher log GUI it shows that Save Structured Data PUT has failed 
![safe-launch-log](https://cloud.githubusercontent.com/assets/12783198/19904531/e687eb4e-a06a-11e6-9936-0addfd37b092.png)

**Comment by scotcoin-southside** [comment]
I have exactly the same problem on Ubuntu 16.04

In addition when running  `npm run start`

I get these errors to the console:
`Html Webpack Plugin:
  Error: Child compilation failed:
  Entry module not found: Error: Cannot resolve 'file' or 'directory' /home/willie/projects/maidsafe/local_development/saf  e_examples/webrtc_app/index.html in /home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app:
  Error: Cannot resolve 'file' or 'directory' /home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app/in  dex.html in /home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app
  
  - compiler.js:76 
    [webrtc_app]/[react-scripts]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:214 Compiler.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:214:10
  
  - Compiler.js:403 
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:403:12
  
  - Tapable.js:67 Compiler.next
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:67:11
  
  - CachePlugin.js:40 Compiler.
    [webrtc_app]/[react-scripts]/[webpack]/lib/CachePlugin.js:40:4
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:400 Compiler.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:400:9
  
  - Compilation.js:577 Compilation.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compilation.js:577:13
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:572 Compilation.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compilation.js:572:10
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:567 Compilation.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compilation.js:567:9
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:563 Compilation.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compilation.js:563:8
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:525 Compilation.seal
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compilation.js:525:7
  
  - From previous event:
  
  - compiler.js:69 Object.compileTemplate
    [webrtc_app]/[react-scripts]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.
    [webrtc_app]/[react-scripts]/[html-webpack-plugin]/index.js:47:40
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:46 Watching.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:46:17
  
  - Tapable.js:67 Compiler.next
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:67:11
  
  - middleware.js:80 Compiler.invalidAsyncPlugin
    [webrtc_app]/[react-scripts]/[webpack-dev-middleware]/middleware.js:80:3
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [webrtc_app]/[react-scripts]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:44 Watching._go
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:44:16
  
  - Compiler.js:36 Watching.
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:36:8
  
  - Compiler.js:302 Compiler.readRecords
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:302:10
  
  - Compiler.js:33 new Watching
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:33:16
  
  - Compiler.js:161 Compiler.watch
    [webrtc_app]/[react-scripts]/[webpack]/lib/Compiler.js:161:17
  
  - middleware.js:105 module.exports
    [webrtc_app]/[react-scripts]/[webpack-dev-middleware]/middleware.js:105:27
  
  - Server.js:53 new Server
    [webrtc_app]/[react-scripts]/[webpack-dev-server]/lib/Server.js:53:20
  
  - start.js:241 runDevServer
    [webrtc_app]/[react-scripts]/scripts/start.js:241:19
  
  - start.js:299 run
    [webrtc_app]/[react-scripts]/scripts/start.js:299:3
  
  - start.js:306 detect.then.port
    [webrtc_app]/[react-scripts]/scripts/start.js:306:5
  
  - next_tick.js:103 process._tickCallback
    internal/process/next_tick.js:103:7`

Guessing this all stems from
`Error: Cannot resolve 'file' or 'directory' /home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app/in  dex.html in /home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app`

index.html is in fact in 
/home/willie/projects/maidsafe/local_development/safe_examples/webrtc_app/**src**/
