### ISSUE TITLE
Web hosting manager links back to browser

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_examples#220]
[Home] PublicID Service name detail on left side, could do with being an actual link to the website in the browser.. with hover suggesting the actual safe url, with "visit url" suggested to tempt that link to browser exists.

Seems that detail atm appear underlined as if a url but does nothing at the moment - or is that just the safe:// in Linux not actioning until the next update??.. still, user would expect perhaps tooltips on urls in hosting manager to tease what each link will do.

**Comment by krishnaIndia** [comment]
This is an bug in  safe_browser where the `safe:`  protocol was not registered properly. This should be fixed in the next release of the browser. This [PR](https://github.com/maidsafe/safe_browser/pull/83) in safe_browser is merged already and should fix the issue.
