### ISSUE TITLE
Help on first use - ABC pointers for noobs

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_examples#222]
Forum sees the expected [new user reaction](https://safenetforum.org/t/level-1-questions-for-safe-browser/15096) "I am seeing the following", "What is this for"

Perhaps on first use a peppering of literal pointers, explaining what should be obvious; those could then age after the user is familiar with some action like authenticating or web hosting etc. Assuming nothing of noobs perhaps will help reassure that they are in a safe environment where there are no surprises - everything is simple?

**Comment by krishnaIndia** [comment]
@davidpbrown, thanks for sharing your thoughts. Will pass this as an input to the design team. These are example applications for the devs to demonstrate the API and the focus has been on that. We do want to improve the user experience certainly. We will take this input of yours and try to do the best. You would be seeing the improvements in the UI & UX in the iterations to follow in steps.

**Comment by hunterlester** [comment]
Have you used Zurb Foundation's Joyride?
http://foundation.zurb.com/sites/docs/v/5.5.3/components/joyride.html
It's a neat component for building new user tours into applications. 

Would this be a useful route?

**Comment by davidpbrown** [comment]
Related: there's no positive feedback on large file uploads.. not even the noise on the commandline there used to be; so, the only route to confidence atm appears to be in the browser refreshing the account status but that's less satisfying than some percentage complete - even if that is %locally fragmented/encrypted before upload.. also, if the delay is more local than on upload, the account refresh perhaps is no measure of progress on a large file?..

Perhaps as %preperation, if confusion with actual upload wants to be avoided.

**Comment by hunterlester** [comment]
Thank you for bringing awareness to these details. This issue is being tracked now.

**Comment by shankar2105** [comment]
Hi @davidpbrown we have created a [task](https://maidsafe.atlassian.net/browse/MAID-2211) to fix this issue.

**Comment by shankar2105** [comment]
Closing the issue as it got resolved with the task [MAID-2211](https://maidsafe.atlassian.net/browse/MAID-2211)
