### ISSUE TITLE
Web Hosting Manager: drag and drop files results in blank white screen

### ISSUE THREAD

**Issue by jimmycuadra** [maidsafe/safe_examples#231]
Operation System: macOS 10.12.6
Web Hosting Manager Version: 0.1.2 (Test 18)

I tried dragging a list of files and directories from the Finder into a web directory (`_public/ruma/www-root` if it matters), and the entire window turned blank white. I couldn't tell if an upload was in progress or not. After more than 5 minutes, the window was still white, so I just quit the program.

**Comment by shankar2105** [comment]
Hi, @jimmycuadra we don't support drag and drop with the latest version of Web hosting manager. We will fix the white screen issue when files get dragged in. Thanks for your support.

**Comment by shankar2105** [comment]
Closing this as the issue got fixed with [MAID-2211](https://maidsafe.atlassian.net/browse/MAID-2211).
