### ISSUE TITLE
Web Hosting Manager sometimes fails to authenticate

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_examples#265]
Sometimes the web hosting manager fails to authorise. Solution is to restart the browser and clear all the authorisations, but this doesn't always work. Same issue as this post I think https://safenetforum.org/t/maidsafe-dev-update-august-31-2017-test-19/15974/20?u=jpl

Logfiles  attached.
[Safe-broswer-log-010917.txt](https://github.com/maidsafe/safe_examples/files/1271530/Safe-broswer-log-010917.txt)

[Safe-auth-log-010917.txt](https://github.com/maidsafe/safe_examples/files/1271463/Safe-auth-log-010917.txt)

**Comment by hunterlester** [comment]
This must have had to do with the maximum number of IP connections being reached and not being released on the client side. All cleared up now. See: https://github.com/maidsafe/safe_browser/pull/164 and https://github.com/maidsafe/crust/pull/858
