### ISSUE TITLE
Web Hosting Manager fails to publish

### ISSUE THREAD

**Issue by PedroSwift** [maidsafe/safe_examples#287]
Mac OS.
Create public ids works.
Create website allows selection of template
Allows creation of service name
Publish button shows selectable, but nothing happens on click..

**Comment by PedroSwift** [comment]
Using "Start from Scratch", was able to create folder, upload index.html, all worked.
My memory from previous tests was that using the template option, a folder was created for yo, but that may be incorrect. There seems to be less explicit file management in this version?

**Comment by boompilot** [comment]
Win 10.
Identical result to PedroSwift's Mac OS report.  Clicking publish appears to do nothing.

**Comment by Sprkz** [comment]
Same as above: WIN 10 -  Publish button fails to publish using Template option

**Comment by hunterlester** [comment]
Hi all,
Thank you for reporting these issues.
It appears that everything has been fixed by latest updated in Web Hosting Manager.
