### ISSUE TITLE
SAFE API Playground - documentation issues with mock browser

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_examples#318]
I'm trying to get mock working with the MaidSafe build of SAFE Browser (0.7.0 mock on Debian) and since I was having trouble, decided to follow [How to develop for the SAFE Network (draft)](https://forum.safedev.org/t/how-to-develop-for-the-safe-network-draft/843?u=happybeing). I skipped past the bit about building SAFE Browser (mock) because I'm using MaidSafe's mock build.

I found two issues with instructions:
1. The forum post (above link) says "Clone this repository" with a link that points to https://github.com/maidsafe/safe_examples/tree/master/safe_web_api_playground. **Issue:** you can't clone that repo, you have to clone safe_examples and then cd into safe_web_api_playgorund.

2. Issue: safe_web_api_playground/README.md fails to mention two essential steps:
 - you must be using the SAFE Browser - mock build - to visit localhost:3003
 - before that will work, you must check that in the browser, File > SAFE Browsing Enabled is *not checked*. Until you do this the page won't load.

**Comment by hunterlester** [comment]
You are the best, Mark. Thank you for pointing all these small things that can cause confusion for many users. I've updated doc and am pushing PR now.
