### ISSUE TITLE
SAFE API Playground - not working with SAFE Browser 0.7.0 (mock - MaidSafe build)

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_examples#319]
I'm trying to get mock working with the MaidSafe build of SAFE Browser (0.7.0 mock on Debian) and since I was having trouble, decided to follow [How to develop for the SAFE Network (draft)](https://forum.safedev.org/t/how-to-develop-for-the-safe-network-draft/843?u=happybeing). I skipped past the bit about building SAFE Browser (mock) because I'm using MaidSafe's mock build.

I'm on Debian (jesse), running SAFE Browser 0.7.0 (mock - although the version info doesn't mention it is mock - another minor issue).

Having followed the README.md instructions to get the API Playground displaying, I click safeApp > initialize. **Issue:** Get a perpetual progress gif, and under the code this appears in red: "Error not yet recognized. Please inform developer."

**Comment by hunterlester** [comment]
Is there anything informative in your dev tools console on the playground page?

The playground should be getting an update soon, anyway.

**Comment by hunterlester** [comment]
How is the playground working for you lately on Debian?

**Comment by bochaco** [comment]
I'm closing this now as the issue was not reported to still be reproducible anymore. Please feel free to re-open it if you still experience the same issues.
