### ISSUE TITLE
sha3Hash example in web_api_playground , async

### ISSUE THREAD

**Issue by wrnice** [maidsafe/safe_examples#340]
The example in the web_api_playground   ( not sure the version... , it is live on codeplay.discover )   for sha3Hash tries to : 
`async () => {
      try {
        hashedString = await window.safeCrypto.sha3Hash(appHandle, '1010101010101');
      } catch (err) {
        return err;
      }
      return `SHA3 Hash generated: ${String.fromCharCode.apply(null, new Uint8Array(**res**))}`;
    }
`

This prints ... nothing...

Here, '**res**' looks like a remnant of the previous version that used .then ,

maybe it should be : 
`      return `SHA3 Hash generated: ${String.fromCharCode.apply(null, new Uint8Array(**hashedString**))}`;`

?

**Comment by hunterlester** [comment]
Ah, yes, thank you!
