### ISSUE TITLE
Immediately creating public service fails when starting directly with folder upload

### ISSUE THREAD

**Issue by subscribernamegoeshere** [maidsafe/safe_examples#36]
I only managed to bring up the testsite http://pacman.safenet when I first waited endlessly and multiple times uploaded my folder (with a single index html and subfolder structure with a few image files and js files)

they multiple times showed upload state at 100% but would never return back nicely to the previous area of the demo app, eventually the demo app always showed that it timedout or lost connection to the launcher.

I repeated this several times for the past tens or so hours

Relaunching the demo app always told me that I already had the pacman public ID registered but I didnt have services.

So then I opted for creating services from the template, then chose the www. prefix and then just left the default template untouched.

It pretty much within seconds completed the 'upload' of that template way to create the www. service, but then I noticed that upon completion of that second way to create the service via the template the site pacman.safenet immediately became alive and live and responsive and would actually load the open sourced packman google anniversary game in the browser

And the file browsing of that public area also showed my index html and pacmans subfolder structure with the images and js of pacman.

So there is something wrong here with the upload mechanism or that some essential publishing steps are lacking or missing or very time sensitive and never completing and only the template-way to do this stuff actually completes the necessary database or safenet structure entries and such stuff.

Thanks.

**Comment by krishnaIndia** [comment]
We did get few feedback on the stability of the uploader. We will certainly improve this by the next release. Thanks @subscribernamegoeshere for reporting the issue.

**Comment by krishnaIndia** [comment]
@subscribernamegoeshere did the [latest release](https://github.com/maidsafe/safe_examples/releases/tag/0.2.1) improve the experience? If yes, then we can get this issue closed.

Cheers!
