### ISSUE TITLE
.safenet not resolved in browser

### ISSUE THREAD

**Issue by taoteh1221** [maidsafe/safe_examples#38]
I created a safe launcher login, logged in, started the safe demo, and granted access to safe launcher. Created my public id / personal files uploaded / website service fine, no issues. But when I try to view the website in my browser it cannot resolve any .safenet domains. My test site is: http://homepage.taoteh1221.safenet/

**Comment by taoteh1221** [comment]
I also cannot locate my private keys to backup for my public id?

**Comment by dirvine** [comment]
On Tue, Mar 1, 2016 at 9:36 PM, Michael Kilday <notifications@github.com>
wrote:

> I also cannot locate my private keys to backup for my public id?


You won't need to, it's backed up on the network already for you and by you
(it'e encrypted in session packets and stored).


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by taoteh1221** [comment]
Groovy, that's a nice feature. How do I get .safenet domains to resolve in my browser though? Reboot did not help. I'm testing on Windows 10.

**Comment by upstate** [comment]
Did you set the proxy settings in your browser?

**Comment by upstate** [comment]
https://maidsafe.readme.io/docs/launcher#set-up-automatic-proxy

**Comment by taoteh1221** [comment]
Oh, so I have to route ALL my browser traffic through http://visualiser.maidsafe.net/safe_proxy.pac?

**Comment by dirvine** [comment]
Only for this intial trial, that will alter as we roll out. For simplicity right now though, yes.

**Comment by taoteh1221** [comment]
Sounds great, thanks for steering me in the right direction...nice platform BTW, very easy to use. Best wishes on your long-awaited success.

**Comment by dirvine** [comment]
:+1:
