### ISSUE TITLE
electron app crashes after launching on OSX

### ISSUE THREAD

**Issue by hems** [maidsafe/safe_examples#39]
After double clicking it it flashes this screen then crashes:

<img width="1136" alt="screen shot 2016-03-02 at 00 28 15" src="https://cloud.githubusercontent.com/assets/27327/13447193/7466e3d6-e011-11e5-849e-05c424b8ee4b.png">

I don't have the safe_launcher installed and running so i suspected that might be the problem?

If that is the reason wouldn't be nice to have a simple check and let the user know about the issue?

for now i'm trying to install the safe_launcher and see if i can figure this out.

**Comment by hems** [comment]
After download safe_launcher binary and double clicking the compiled app from safe_examples the same problem still happen.

Downloading the binary from [here](https://github.com/maidsafe/safe_examples/releases) results in the same problem.

OSX 10.10.1

**Comment by krishnaIndia** [comment]
Can you please try the [latest version](https://github.com/maidsafe/safe_examples/releases/tag/0.2.1) and confirm if things are working fine now?
