### ISSUE TITLE
Launcher Demo App (OSX): Cannot select files

### ISSUE THREAD

**Issue by kpowick** [maidsafe/safe_examples#43]
On OSX 10.11.13, the _Launcher Demo App_ does not allow one to select files for the demos: _Manage Websites and Files_, and _View and Manage Private Data_.

With either of those demos, if one uses the option to upload individual files, a file selection dialogue is displayed, but all files listed are greyed-out and non-selectable.  Only entire folders may be selected. i.e. The option to select files behaves in exactly the same way as the option to select folders. 

I did try to _drag & drop_ a file onto the _View and Manage Private Data_ demo, but that resulted in the image file I used being displayed within the Launcher Demo window, leaving me with no way to return to the demo interface.  I had to quit and restart the Launcher Demo.

**Comment by bekman1** [comment]
same problem

**Comment by krishnaIndia** [comment]
Should be resolved with the [release version 0.2.1](https://github.com/maidsafe/safe_examples/releases/tag/0.2.1)

**Comment by kpowick** [comment]
Yes, this is resolved for me in the latest version of the Launcher and Demo Apps.
