### ISSUE TITLE
The version number is duplicated in safe_api_factory.js

### ISSUE THREAD

**Issue by afck** [maidsafe/safe_examples#61]
That is easy to overlook in version updates: https://github.com/maidsafe/safe_examples/pull/60

**Comment by Viv-Rajkumar** [comment]
can't we just have this pulled in with `require('../../package.json').version` ?

**Comment by krishnaIndia** [comment]
This is fixed in this [pr](https://github.com/maidsafe/safe_examples/pull/63)
