### ISSUE TITLE
Demo app loses connection with SAFE Launcher 

### ISSUE THREAD

**Issue by polpolrene** [maidsafe/safe_examples#65]
WIN 10/64

When uploading files 1-by-1 to the private data map the demo app hangs at 25%. After some time it says it lost the connection with the Launcher and gives a message that the Launcher should be running, even while this is already the case. This bug shows up now and then, so it might work to upload 5 or 6 little 4MB. files but after a while it's impossible to upload more, even while there's no client limit reached or something. The only way to fix this is to close both the demo app and Launcher and restart them again. After a while (and sometimes very soon) this bug shows up again.

**Comment by krishnaIndia** [comment]
This should be resolved in the latest version 0.4.0.

Thanks @polpolrene
