### ISSUE TITLE
Private Data upload progression never over 25%

### ISSUE THREAD

**Issue by polpolrene** [maidsafe/safe_examples#66]
WIN 10/64

When uploading private data using the demo app, the progression bar doesn't indicate the right value for the upload. In testing 4 MB. files the progression bar hangs at 25% even while after some time the file is uploaded correctly and shows up in the list. The same thing shows up when an upload doesn't work right and the demo app gives an error. It never goes beyond 25% as far as I've seen.

**Comment by sungminz** [comment]
Same thing is happening to me exactly.  Any upload gets stuck at 24% whether it finishes or not.  Have to close vault, launcher, and demo app to get back in.  Windows 7 X64.  Tried running apps as admin and not, same thing happens.

**Comment by krishnaIndia** [comment]
Please do re-open the issue if it still persists in [v0.4.0](https://github.com/maidsafe/safe_examples/releases/tag/0.4.0). Thanks @polpolrene & @sungminz
