### ISSUE TITLE
Failed to create directory 

### ISSUE THREAD

**Issue by 19eddyjohn75** [maidsafe/safe_examples#69]
I can't even upload anything 
https://ipfs.pics/QmfGcoGAA56aNmt4aswWG3v3UWRXmHUNq7PS1bH6pJg9CM

Not even, **Use our template to create a simple example site** works

Launcher Demo App v0.2.3

**Comment by Lariat419** [comment]
I have a similar problem.
v0.4.6-osx-x64

Used to let me upload and then just stopped and gives me the same file upload error. Tried deleting any files with the same name. Tried to restarting the SAFE Launcher and MaidSafe DemoApp v0.2.2-osx-x64
tried different files and from different drives. 
Also tried making new pages with no luck.

**Comment by krishnaIndia** [comment]
Please try the [v0.4.0](https://github.com/maidsafe/safe_examples/releases/tag/0.4.0) with launcher v0.6.0. Please do re-open the issue, if the problem still persists
