### ISSUE TITLE
Progress bar / loading graphic when uploading (UI suggestion)

### ISSUE THREAD

**Issue by aenemic** [maidsafe/safe_examples#80]
The progress bar finishes quickly, but after that the loading graphic runs for longer than the progress bar in case of small files. Makes the experience feel more sluggish compared to not having additional loading after the progress bar finishes.

**Comment by krishnaIndia** [comment]
Agreed, this will be patched in the next updated.

**Comment by krishnaIndia** [comment]
Resolved in [v0.4.0](https://github.com/maidsafe/safe_examples/releases/tag/0.4.0). Thanks @aenemic
