### ISSUE TITLE
Deleting files in public / website folder extremely slow

### ISSUE THREAD

**Issue by aenemic** [maidsafe/safe_examples#81]
Title says it all, tested on several OS

**Comment by aenemic** [comment]
Additional: after deleting index.html from a template and uploading my own, I get a "filename already exist error"

**Comment by krishnaIndia** [comment]
Will try to test this scenario and fix it if reproducible. Should be reproducible I think.

Thanks again!

**Comment by fiee** [comment]
Deleting is still extremely slow. (Current app set on OSX)

**Comment by krishnaIndia** [comment]
This is related to  the speed of the network. At present the vaults are being throttled to be slow in testnets to simulate slow networks and identify the issues around those scenarios.

The speed of the network will be good once the features get stablised
