### ISSUE TITLE
Creating web Failed

### ISSUE THREAD

**Issue by madmaxero** [maidsafe/safe_examples#82]
Failed to upload Template
Failed to create directory /public/cinetotal CoreError::MutationFailure::MutationError::LowBalance
OK

**Comment by krishnaIndia** [comment]
This looks like a valid error, @madmaxero . The upload has failed because of 100 put requests made by the user account.
I hope you had uploaded files and consumed some space before trying to upload the template. If my assumption is right can we close this issue?

**Comment by madmaxero** [comment]
Yes its like that.

**Comment by krishnaIndia** [comment]
Thanks for confirming. I will close this issue then.
