### ISSUE TITLE
Uploaded private data is 0 bytes

### ISSUE THREAD

**Issue by fatek** [maidsafe/safe_examples#84]
I am using maidsafe_demo_app-v0.3.1-linux-x64

I uploaded a directory containing 50 files with a total size less than 1 MB. The smallest file is 2 KB and the largest is 109 KB and these two files were successfully uploaded. The directory contents are sorted alphabetically and it is the 31st file onward that all failed to upload with the exception of file number 43 for some reason.

**Comment by krishnaIndia** [comment]
Thanks @fatek, we will improve the user experience in this regards in the next patch version of the demo app.
