### ISSUE TITLE
Upload dialog says "Directory" when choosing a single file

### ISSUE THREAD

**Issue by fatek** [maidsafe/safe_examples#85]
The program's behaviour is correct. It is just that the text is incorrect and may cause confusion.

![file-upload](https://cloud.githubusercontent.com/assets/12451793/16508845/e8378a52-3eeb-11e6-8218-2a7a760427ec.png)

**Comment by krishnaIndia** [comment]
Will fix this in the next patch update. Thanks again

**Comment by krishnaIndia** [comment]
Resolved in [v0.4.0](https://github.com/maidsafe/safe_examples/releases/tag/0.4.0)
