### ISSUE TITLE
Delete not actioned - diff between Manage Public Files and Manage Services

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_examples#87]
Version: maidsafe_demo_app-v0.3.1-linux-x64

Edit files in Manage Public Files, suggests delete has worked.. and is consistent in then not showing files and folders that were deleted. However, Managed Services still shows those services and visiting them, the full retrieval of files is successful; so, evidently those files are not removed.. yet still the Manage Public Files does not show them, suggesting some confusion there.

Perhaps delete service is different but the option to delete the folder in /public/ while in the Manage Public Files exists.. if user navigates up from the service folder to the /public/, they see a list of all the services as folders.. and I tried to remove those I didn't want to clean up udhr.safenet - so Manage Services shows the reality that en-en.udhr.safenet; ar-ar.udhr.safenet; zh-zh.udhr.safenet all exist still, yet the Manage Public Files pretends they are deleted in the way intended.

**Comment by davidpbrown** [comment]
Looking closer, I wonder this is more about the folder not deleting properly. Files removed seem properly not to be available. So, zh-zh.udhr,safenet files are not available for a visit, though that service is listed - that following my deleting the files first and then looking to delete the folder. The other two ar-ar.udhr.safenet and en-en.udhr.safenet still work, where I'd seen option to remove the folder=service, expecting that the folder=service and its contents to be purged.

**Comment by AxlMaid** [comment]
The delete button does not work at all for me. I presse delete next to the file or folder and nothing happens.

Let me know if you need more information in order to debug.

Thanks,

Axl
<img width="930" alt="screen shot 2017-07-17 at 00 27 09" src="https://user-images.githubusercontent.com/30219645/28251884-bc99942c-6a86-11e7-8c12-f6bc8002b1aa.png">

**Comment by davidpbrown** [comment]
@AxlMaid Try again with Test18 and relog? I'm going to close this one as it's mine from 2016 and not relevant for current tests.
