### ISSUE TITLE
Failed upload results in inability to reupload

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_examples#95]
Okay I tried creating my usual quotes archive site.   It got to 14% and stalled.   So I restarted the demo/launcher.    But now the puts seem to be there but the service isn't registered.   And I can't reupload the site because it says the public folder is still there.

![screenshot from 2016-07-15 15 01 08](https://cloud.githubusercontent.com/assets/6963648/16889703/26a9aae2-4a9d-11e6-9e8b-3f75ecc5229f.png)
![screenshot from 2016-07-15 15 01 47](https://cloud.githubusercontent.com/assets/6963648/16889705/290ef22e-4a9d-11e6-9199-6eb308ade7eb.png)

**Comment by krishnaIndia** [comment]
@Blindsite this should be resolved in the version 0.4.0 of demo app. If you come across this again, please do re-open this issue.

Thanks!
