### ISSUE TITLE
corrupt file

### ISSUE THREAD

**Issue by citan** [maidsafe/safe_examples#96]
Launcher Demo App v0.4.0
OS: Win 10 64, Excel 2010.

Dear Maidsafe team,

1. I uploaded [this Excel file](https://drive.google.com/open?id=0B3_dsOr7ReC3YmQtVklfOHNaczQ) successfully to my private data folder.
2. When I download this file by double clicking on its name, once the download completes, Excel opens but sends out an error (cf. [capture.png](https://drive.google.com/open?id=0B3_dsOr7ReC3WklFdVM5WGpiSGc) and [capture2.png](https://drive.google.com/open?id=0B3_dsOr7ReC3RDFYSUFBdWZrOVk)).
3. I reproduced the error with several Excel files I tried to upload.

This error did not happen in previous versions, only once in March, referenced in atlassian [here](https://maidsafe.atlassian.net/browse/CS-8?jql=text%20~%20%22citan%22%20ORDER%20BY%20updated%20DESC)

Hope this will be useful to you,
Regards,

**Comment by citan** [comment]
in version 0.5.1, the error does not appear anymore, but, instead of excel opening when the download is complete, windows file explorer now opens to a temp folder showing the excel file. Is this intentional ?

**Comment by Viv-Rajkumar** [comment]
> in version 0.5.1, the error does not appear anymore

👍 

>  instead of excel opening when the download is complete, windows file explorer now opens to a temp folder showing the excel file. Is this intentional ?

Yep, It was something raised from the forum to prevent accidental "running" of downloaded corrupt/malicious files.

It was part of v0.5.0. [Changelog](https://github.com/maidsafe/safe_examples/blob/master/demo_app/CHANGELOG.MD#050)

> Open the download folder instead of opening the downloaded file
