### ISSUE TITLE
Demo app keeps hanging at 99%

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_examples#98]
The demo app keeps hanging at 99%.   I've tried restarting the demo app and launcher and the problem still persists.    Which just compounds this issue.

https://github.com/maidsafe/safe_examples/issues/95

I keep spending puts but not getting access to any data.

**Comment by Dahmx** [comment]
No amount of waiting allows the transfer (private file) to complete. Upon exiting and restarting sometimes you find file has uploaded and is available, but mostly the put is spent and no file. The ratio seemed to be 1 completed put to 8 misses.

**Comment by Blindsite** [comment]
I was using Win 7 for most of my uploads and Fedora Linux for a few others.   Same result.   Again Test Network 6.   In my case it was all public files.

**Comment by upstate** [comment]
It's being addressed - https://forum.safenetwork.io/t/safe-network-test-6/10291/292

**Comment by krishnaIndia** [comment]
This should be resolved in the version 0.4.0
